language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip3 install -r requirements.txt
# command to run tests
script:
  - cd ./yw_website/
  - python3 manage.py makemigrations
  - python3 manage.py migrate 
  - python3 manage.py makemigrations website
  - python3 manage.py migrate website
  - python3 manage.py create_test_database
  - python3 manage.py rebuild_index --noinput
  - python3 manage.py test


matrix:
  fast_finish: true

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: develop
