language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip3 install -r requirements.txt
# command to run tests
script:
  - cd ./scripts/
  - ./deploy_python3.sh

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: develop
