# Generated by Django 2.1.1 on 2018-11-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script_upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='workflow',
            field=models.ImageField(default='workflow.png', upload_to='document/'),
        ),
    ]
