# Generated by Django 2.1.3 on 2018-11-13 23:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yw_db', '0002_tag_parent_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TagRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TagVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TagWorkflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='run',
            old_name='time_stamp',
            new_name='run_time_stamp',
        ),
        migrations.RemoveField(
            model_name='file',
            name='checksum',
        ),
        migrations.RemoveField(
            model_name='file',
            name='file_tag',
        ),
        migrations.RemoveField(
            model_name='run',
            name='run_tag',
        ),
        migrations.RemoveField(
            model_name='runfile',
            name='time_stamp',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='parent_tag',
        ),
        migrations.RemoveField(
            model_name='version',
            name='version_tag',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='workflow_tag',
        ),
        migrations.AddField(
            model_name='file',
            name='file_checksum',
            field=models.CharField(default=None, max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='file',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='last_modified_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 13, 23, 25, 50, 178622, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='run',
            name='version_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='yw_db.Version'),
        ),
        migrations.AddField(
            model_name='tag',
            name='parent_tag_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent_tag', to='yw_db.Tag'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='file',
            name='input_data',
            field=models.FileField(upload_to='recon_files/'),
        ),
        migrations.AlterField(
            model_name='runfile',
            name='file_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yw_db.File'),
        ),
        migrations.AlterField(
            model_name='runfile',
            name='run_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yw_db.Run'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_type',
            field=models.CharField(choices=[('w', 'Workflow'), ('v', 'Version'), ('r', 'Run'), ('f', 'File')], default='w', max_length=1),
        ),
        migrations.AlterField(
            model_name='version',
            name='last_modified',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='version',
            name='script_check_sum',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='version',
            name='workflow_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='yw_db.WorkFlow'),
        ),
        migrations.AlterField(
            model_name='version',
            name='yw_model_check_sum',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='version',
            name='yw_model_output',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='description',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='tagworkflow',
            name='tag_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags_workflows', to='yw_db.Tag'),
        ),
        migrations.AddField(
            model_name='tagworkflow',
            name='workflow_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows_tags', to='yw_db.WorkFlow'),
        ),
        migrations.AddField(
            model_name='tagversion',
            name='tag_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags_versions', to='yw_db.Tag'),
        ),
        migrations.AddField(
            model_name='tagversion',
            name='version_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions_tags', to='yw_db.Version'),
        ),
        migrations.AddField(
            model_name='tagrun',
            name='run_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs_tags', to='yw_db.Run'),
        ),
        migrations.AddField(
            model_name='tagrun',
            name='tag_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags_runs', to='yw_db.Tag'),
        ),
        migrations.AddField(
            model_name='tagfile',
            name='file_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files_tags', to='yw_db.File'),
        ),
        migrations.AddField(
            model_name='tagfile',
            name='tag_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags_files', to='yw_db.Tag'),
        ),
    ]
