# Generated by Django 2.1.3 on 2018-11-14 00:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('yw_db', '0005_auto_20181114_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='last_modified_time_stamp',
        ),
        migrations.AddField(
            model_name='file',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 14, 0, 39, 21, 361129, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tagworkflow',
            name='workflow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yw_db.Workflow'),
        ),
        migrations.AlterField(
            model_name='version',
            name='workflow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yw_db.Workflow'),
        ),
    ]
