# Generated by Django 2.1.3 on 2018-11-14 02:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('yw_db', '0008_auto_20181114_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 14, 2, 29, 18, 395245, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tagworkflow',
            name='workflow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yw_db.Workflow'),
        ),
        migrations.AlterField(
            model_name='version',
            name='workflow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yw_db.Workflow'),
        ),
        migrations.AlterUniqueTogether(
            name='tagfile',
            unique_together={('tag', 'file')},
        ),
        migrations.AlterUniqueTogether(
            name='tagrun',
            unique_together={('tag', 'run')},
        ),
        migrations.AlterUniqueTogether(
            name='tagversion',
            unique_together={('tag', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='tagworkflow',
            unique_together={('tag', 'workflow')},
        ),
    ]
